dist: xenial
language: python
sudo: false
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 3.9-dev
# blocklist branches
branches:
  except:
  - requires-io-master
  - /^dependabot.*$/
install:
  - pip install -r requirements-tests.txt
  - pip install coveralls wheel
script:
  - "py.test --pc tests/pyramid.test.ini --cov pytest_pyramid tests/ -p no:pytest_pyramid"
after_success:
  - coveralls
jobs:
  include:
  - stage: linters
    install:
    - pip install -r requirements-lint.txt
    script:
    - pycodestyle
    - pydocstyle
    after_success: skip
  - stage: deploy
    if: tag IS present
    script: skip
    deploy:
      provider: pypi
      user: fizyk
      password:
        secure: AeTVshEncgd/rpqmTNeRYhTOgI4Pgw7h0lMMoqx+6xvAcpJKBi6TRqTSJ5J4zncVbMIXnDhmJl+Ftz4eFwNxkgR2D8IMUZZ2XlzU2FMvDPVQc+xNxJ6r9+xJfv6ROLWFSYiEeE+ELHb+WjcvRk9wBbiUr2TYzlI2nZipuXd9Hs0=
      on:
        tags: true
        repo: fizyk/pytest_pyramid
      distributions: "sdist bdist_wheel"
