name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v1.6.2
    with:
      python-versions: '["3.8", "3.9", "3.10"]'
